name: .NET

#on..:
  #push:
    #branches: [ workitem ]
  ##pull_request:
    #branches: [ Integration ]
on:
   #schedule:
    #- cron: '0 0 * * *'
   push:
     branches:
     #- Workitem
     - branch_5106
     - test
   pull_request:
    branches:
     - master
     - workitem
     - Integratiion

jobs:
  build:

    runs-on: ubuntu-latest
    
    #env:
     # SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      with:
        status: ${{ job.status }} # required
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        steps: ${{toJson(steps)}}
      env:
        SLACK_CHANNEL: cicd
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
       # SLACK_ICON: https://github.com/rtCamp.png?size=48
        #SLACK_MESSAGE: 'Post Content :rocket:'
        #SLACK_TITLE: Post Title
        #SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

      
   # - uses: act10ns/slack@v1
    #  with: 
    #   status: ${{ job.status }}
     #  channel: 'cicd'
      
  #  - name: slack integration
   # - uses: ravsamhq/notify-slack-action@v1
    # with:
     #  status: ${{ job.status }} # required
      # steps: ${{toJson(steps)}}
       #channel: 'cicd'
  #deploy_to_dev:
   # runs-on: ubuntu-latest
    #needs: build
    #if: github.event_name != 'pull_request'
    #environment: Deployment
    #steps:
     #  - name: running deployment script
      #   run: echo "deployment ...."
#comment
#comment1
#commen3
