#codeowner testing1111
#added comment1
##
#1.0
#2.o
#3.0
#4.0
name: .NET

#on:
  #push:
    #branches: [ workitem ]
  #pull_request:
    #branches: [ Integratiion ]
on:
   #schedule:
    #- cron: '0 0 * * *'
   #push:
     #branches:
     #- Workitem
   pull_request:
    branches:
     - master
     - workitem
     - Integratiion

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  deploy_to_dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    environment: Deployment
    steps:
       - name: running deployment script
         run: echo "deployment ...."
#comment
#comment1
#commen3
