name: .NET

#on:
  #push:
    #branches: [ workitem ]
  #pull_request:
    #branches: [ Integration ]
on:
   #schedule:
    #- cron: '0 0 * * *'
   push:
     branches:
     #- Workitem
     - branch_5106
   pull_request:
    branches:
     - master
     - workitem
     - Integratiion

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: slack integration
    - uses: ravsamhq/notify-slack-action@v1
      if: always()
      with:
       status: ${{ job.status }} # required
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required

  #deploy_to_dev:
   # runs-on: ubuntu-latest
    #needs: build
    #if: github.event_name != 'pull_request'
    #environment: Deployment
    #steps:
     #  - name: running deployment script
      #   run: echo "deployment ...."
#comment
#comment1
#commen3
