##############comment2
name: .NET

#on:
  #push:
    #branches: [ workitem ]
  #pull_request:
   # branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  #sonarQubeTrigger:
    #name: SonarQube Trigger
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@master
    #- name: SonarQube Scan
     # uses: kitabisa/sonarqube-action@v1.1.0
      #with:
      #  host: ${{ secrets.SONARQUBE_HOST }}
        #login: ${{ secrets.SONARQUBE_TOKEN }}
