
name: .NET


on:
   
   push:
     branches:
     - branch**
     - master
     - master**
   pull_request:
    branches:
     - master
     - workitem
     - Integratiion

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:

      # Git Checkout
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          
          fetch-depth: 0

      # MegaLinter
      - name: MegaLinter
        id: ml
        
        uses: megalinter/megalinter@v5
        env:
          DISABLE_ERRORS: true
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
      # Upload MegaLinter artifacts
      - name: Archive production artifacts
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: MegaLinter reports
          path: |
            report
            mega-linter.log

