#comment
name: .NET

on:
  #push:
    #branches: [ workitem ]
  #pull_request:
    #branches: [ Integration ]
    
  workflow_dispatch:
    inputs:
      v1:
        description: 'branch'
        required: true
        #default: '2.5.3'
      v2:
        description: 'input2'
        required: true
        default: 'true'

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Set Flutter version
    - uses: subosito/flutter-action@v2.2.0
      with:
          flutter-version: '${{ github.event.inputs.v1}}'

  deploy_to_dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    environment: Deployment
    steps:
       - name: running deployment script
         run: echo "deployment ...."

